curriculum/config/routes.rb
Curriculum::Application.routes.draw do
  
  resources :courses
  
  resources :prerequisites

  resources :term_plans

  resources :degree_requirements

  resources :degree_plan_notes

  resources :degree_plans

  resources :undergrad_programs
  
  resources :depts

  resources :colleges

end

curriculum/app/models/college.rb
class College < ActiveRecord::Base
  has_many :depts
end

curriculum/app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render action: 'show', status: :created, location: @college }
      else
        format.html { render action: 'new' }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :acronym, :org_code)
    end
end

curriculum/app/helpers/colleges_helper.rb
module CollegesHelper
end

curriculum/app/views/colleges/_form.html.erb
<%= form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym %>
  </div>
  <div class="field">
    <%= f.label :org_code %><br>
    <%= f.text_field :org_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

curriculum/app/views/colleges/edit.html.erb
<h1>Editing college</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

curriculum/app/views/colleges/index.html.erb
<h1>Listing colleges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Acronym</th>
      <th>Org code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.acronym %></td>
        <td><%= college.org_code %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %>

curriculum/app/views/colleges/new.html.erb
<h1>New college</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

curriculum/app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @college.acronym %>
</p>

<p>
  <strong>Org code:</strong>
  <%= @college.org_code %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>