curriculum/config/routes.rb
Curriculum::Application.routes.draw do
  
  resources :courses
  
  resources :prerequisites

  resources :term_plans

  resources :degree_requirements

  resources :degree_plan_notes

  resources :degree_plans

  resources :undergrad_programs
  
  resources :depts

  resources :colleges

end

curriculum/app/models/degree_plan.rb
class DegreePlan < ActiveRecord::Base
  has_many :degree_plan_notes
  belongs_to :undergrad_program
  has_many :term_plans
end

curriculum/app/controllers/degree_plans_controller.rb
class DegreePlansController < ApplicationController
  before_action :set_degree_plan, only: [:show, :edit, :update, :destroy]

  # GET /degree_plans
  # GET /degree_plans.json
  def index
    @degree_plans = DegreePlan.all
  end

  # GET /degree_plans/1
  # GET /degree_plans/1.json
  def show
  end

  # GET /degree_plans/new
  def new
    @degree_plan = DegreePlan.new
  end

  # GET /degree_plans/1/edit
  def edit
  end

  # POST /degree_plans
  # POST /degree_plans.json
  def create
    @degree_plan = DegreePlan.new(degree_plan_params)

    respond_to do |format|
      if @degree_plan.save
        format.html { redirect_to @degree_plan, notice: 'Degree plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @degree_plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @degree_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degree_plans/1
  # PATCH/PUT /degree_plans/1.json
  def update
    respond_to do |format|
      if @degree_plan.update(degree_plan_params)
        format.html { redirect_to @degree_plan, notice: 'Degree plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @degree_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degree_plans/1
  # DELETE /degree_plans/1.json
  def destroy
    @degree_plan.destroy
    respond_to do |format|
      format.html { redirect_to degree_plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree_plan
      @degree_plan = DegreePlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_plan_params
      params.require(:degree_plan).permit(:undergrad_program_id, :academic_year)
    end
end

curriculum/app/helpers/degree_plans_helper.rb
module DegreePlansHelper
end

curriculum/app/views/degree_plans/_form.html.erb
<%= form_for(@degree_plan) do |f| %>
  <% if @degree_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree_plan.errors.count, "error") %> prohibited this degree_plan from being saved:</h2>

      <ul>
      <% @degree_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :undergrad_program_id %><br>
    <%= f.number_field :undergrad_program_id %>
  </div>
  <div class="field">
    <%= f.label :academic_year %><br>
    <%= f.text_field :academic_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

curriculum/app/views/degree_plans/edit.html.erb
<h1>Editing degree_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @degree_plan %> |
<%= link_to 'Back', degree_plans_path %>

curriculum/app/views/degree_plans/index.html.erb
<h1>Listing degree_plans</h1>

<table>
  <thead>
    <tr>
      <th>Undergrad program</th>
      <th>Academic year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @degree_plans.each do |degree_plan| %>
      <tr>
        <td><%= degree_plan.undergrad_program_id %></td>
        <td><%= degree_plan.academic_year %></td>
        <td><%= link_to 'Show', degree_plan %></td>
        <td><%= link_to 'Edit', edit_degree_plan_path(degree_plan) %></td>
        <td><%= link_to 'Destroy', degree_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degree plan', new_degree_plan_path %>

curriculum/app/views/degree_plans/new.html.erb
<h1>New degree_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', degree_plans_path %>

curriculum/app/views/degree_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Undergrad program:</strong>
  <%= @degree_plan.undergrad_program_id %>
</p>

<p>
  <strong>Academic year:</strong>
  <%= @degree_plan.academic_year %>
</p>

<%= link_to 'Edit', edit_degree_plan_path(@degree_plan) %> |
<%= link_to 'Back', degree_plans_path %>