curriculum/config/routes.rb
Curriculum::Application.routes.draw do
  
  resources :courses
  
  resources :prerequisites

  resources :term_plans

  resources :degree_requirements

  resources :degree_plan_notes

  resources :degree_plans

  resources :undergrad_programs
  
  resources :depts

  resources :colleges

end

curriculum/app/models/dept.rb
class Dept < ActiveRecord::Base
  belongs_to :college
  has_many :undergrad_programs
  has_many :courses
end

curriculum/app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.all
  end

  # GET /depts/1
  # GET /depts/1.json
  def show
  end

  # GET /depts/new
  def new
    @dept = Dept.new
  end

  # GET /depts/1/edit
  def edit
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(dept_params)

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dept }
      else
        format.html { render action: 'new' }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depts/1
  # PATCH/PUT /depts/1.json
  def update
    respond_to do |format|
      if @dept.update(dept_params)
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept.destroy
    respond_to do |format|
      format.html { redirect_to depts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dept
      @dept = Dept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dept_params
      params.require(:dept).permit(:college_id, :name, :acronym, :org_code)
    end
end

curriculum/app/helpers/depts_helper.rb
module DeptsHelper
end

curriculum/app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :college_id %><br>
    <%= f.number_field :college_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym %>
  </div>
  <div class="field">
    <%= f.label :org_code %><br>
    <%= f.text_field :org_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

curriculum/app/views/depts/edit.html.erb
<h1>Editing dept</h1>

<%= render 'form' %>

<%= link_to 'Show', @dept %> |
<%= link_to 'Back', depts_path %>

curriculum/app/views/depts/index.html.erb
<h1>Listing depts</h1>

<table>
  <thead>
    <tr>
      <th>College</th>
      <th>Name</th>
      <th>Acronym</th>
      <th>Org code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
        <td><%= dept.college_id %></td>
        <td><%= dept.name %></td>
        <td><%= dept.acronym %></td>
        <td><%= dept.org_code %></td>
        <td><%= link_to 'Show', dept %></td>
        <td><%= link_to 'Edit', edit_dept_path(dept) %></td>
        <td><%= link_to 'Destroy', dept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dept', new_dept_path %>

curriculum/app/views/depts/new.html.erb
<h1>New dept</h1>

<%= render 'form' %>

<%= link_to 'Back', depts_path %>

curriculum/app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>College:</strong>
  <%= @dept.college_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dept.name %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @dept.acronym %>
</p>

<p>
  <strong>Org code:</strong>
  <%= @dept.org_code %>
</p>

<%= link_to 'Edit', edit_dept_path(@dept) %> |
<%= link_to 'Back', depts_path %>