curriculum/config/routes.rb
Curriculum::Application.routes.draw do
  
  resources :courses
  
  resources :prerequisites

  resources :term_plans

  resources :degree_requirements

  resources :degree_plan_notes

  resources :degree_plans

  resources :undergrad_programs
  
  resources :depts

  resources :colleges

end

curriculum/app/models/term_plan.rb
class TermPlan < ActiveRecord::Base
  belongs_to :degree_plan
  has_and_belongs_to_many :degree_requirements
end

curriculum/app/controllers/term_plans_controller.rb
class TermPlansController < ApplicationController
  before_action :set_term_plan, only: [:show, :edit, :update, :destroy]

  # GET /term_plans
  # GET /term_plans.json
  def index
    @term_plans = TermPlan.all
  end

  # GET /term_plans/1
  # GET /term_plans/1.json
  def show
  end

  # GET /term_plans/new
  def new
    @term_plan = TermPlan.new
  end

  # GET /term_plans/1/edit
  def edit
  end

  # POST /term_plans
  # POST /term_plans.json
  def create
    @term_plan = TermPlan.new(term_plan_params)

    respond_to do |format|
      if @term_plan.save
        format.html { redirect_to @term_plan, notice: 'Term plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @term_plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @term_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /term_plans/1
  # PATCH/PUT /term_plans/1.json
  def update
    respond_to do |format|
      if @term_plan.update(term_plan_params)
        format.html { redirect_to @term_plan, notice: 'Term plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @term_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /term_plans/1
  # DELETE /term_plans/1.json
  def destroy
    @term_plan.destroy
    respond_to do |format|
      format.html { redirect_to term_plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term_plan
      @term_plan = TermPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_plan_params
      params.require(:term_plan).permit(:degree_plan_id, :term_number)
    end
end

curriculum/app/helpers/term_plans_helper.rb
module TermPlansHelper
end

curriculum/app/views/term_plans/_form.html.erb
<%= form_for(@term_plan) do |f| %>
  <% if @term_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term_plan.errors.count, "error") %> prohibited this term_plan from being saved:</h2>

      <ul>
      <% @term_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :degree_plan_id %><br>
    <%= f.number_field :degree_plan_id %>
  </div>
  <div class="field">
    <%= f.label :term_number %><br>
    <%= f.number_field :term_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

curriculum/app/views/term_plans/edit.html.erb
<h1>Editing term_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @term_plan %> |
<%= link_to 'Back', term_plans_path %>

curriculum/app/views/term_plans/index.html.erb
<h1>Listing term_plans</h1>

<table>
  <thead>
    <tr>
      <th>Degree plan</th>
      <th>Term number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @term_plans.each do |term_plan| %>
      <tr>
        <td><%= term_plan.degree_plan_id %></td>
        <td><%= term_plan.term_number %></td>
        <td><%= link_to 'Show', term_plan %></td>
        <td><%= link_to 'Edit', edit_term_plan_path(term_plan) %></td>
        <td><%= link_to 'Destroy', term_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term plan', new_term_plan_path %>

curriculum/app/views/term_plans/new.html.erb
<h1>New term_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', term_plans_path %>

curriculum/app/views/term_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree plan:</strong>
  <%= @term_plan.degree_plan_id %>
</p>

<p>
  <strong>Term number:</strong>
  <%= @term_plan.term_number %>
</p>

<%= link_to 'Edit', edit_term_plan_path(@term_plan) %> |
<%= link_to 'Back', term_plans_path %>